baseURL = "http://orasql.ru"
languageCode = "en-us"
title = "Учебник Oracle SQL, PL/SQL"
theme= "orasqlru-theme"

[params]
  brand="Orasql.ru"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'github'
tabWidth = 4
